
/* $NoKeywords:$ */
/**
 * @file
 *
 * @e \$Revision:$   @e \$Date:$
 */
 /*****************************************************************************
  *
  * Copyright (C) 2016-2022 Advanced Micro Devices, Inc. All rights reserved.
  *
  *******************************************************************************
  **/


#include "MyPorting.h"
#include <RV/APCB.h>
#include <ApcbCustomizedDefinitions.h>
#include <ApcbDefaults.h>

CHAR8 mDummyBuf;

APCB_TYPE_DATA_START_SIGNATURE();
APCB_TYPE_HEADER       ApcbTypeHeader = {
  APCB_GROUP_FCH,
  APCB_FCH_TYPE_CONFIG_DEFAULT_PARAMETERS,
  (
    sizeof (APCB_TYPE_HEADER)
  ),
  0,
  0,
  0
};  // SizeOfType will be fixed up by tool

APCB_PARAM_ATTRIBUTE  ParameterListDefaultsAttribute[] = {
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_CONSOLE_OUT_ENABLE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_CONSOLE_OUT_SERIAL_PORT, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ASSERT_ENABLE, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_TURTLE_BOOT_ENABLE, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ELEVATE_SMBUS_CLOCK, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_UART_BAUD_RATE, sizeof (UINT32) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ABL_DEBUG_PRINT_SERIAL_PORT_DETECT_EN, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_ABL_INIT_ENABLE, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IO80_ENABLE, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_KBC6064_ENABLE, sizeof (BOOLEAN) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_CLOCK, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IOMODE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_ALERT_MODE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE0_SIZE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE1_SIZE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE2_SIZE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE3_SIZE, sizeof (UINT8) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE0_BASE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE1_BASE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE2_BASE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_IORANGE3_BASE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE0_SIZE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE1_SIZE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE2_SIZE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE3_SIZE, sizeof (UINT16) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE0_BASE, sizeof (UINT32) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE1_BASE, sizeof (UINT32) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE2_BASE, sizeof (UINT32) - 1, 0},
  {APCB_TIME_POINT_ANY, APCB_TOKEN_CONFIG_FCH_ESPI_MMIORANGE3_BASE, sizeof (UINT32) - 1, 0},
  {0, APCB_TOKEN_CONFIG_LIMIT, 0, 0},
};

_1BYTE_ALIGN UINT8  ParameterListDefaultsValue[] = {
  BSU08 (BLDCFG_FCH_CONSOLE_OUT_ENABLE),               //< BMC SOcket Number
  BSU08 (BLDCFG_FCH_CONSOLE_OUT_SERIAL_PORT),          //< BMC Start Lane
  BSBLN (BLDCFG_FCH_ASSERT_ENABLE),                    //< ASSERTs enable
  BSBLN (BLDCFG_FCH_TURTLE_BOOT_ENABLE),               //< Turtle Boot Mode Enable
  BSBLN (BLDCFG_FCH_ELEVATE_SMBUS_CLOCK),              //< Elevate Smbus Clock Enable
  BSU32 (BLDCFG_FCH_UART_BAUD_RATE),                   //< FCH UART Baud rate
  BSBLN (BLDCFG_FCH_ABL_DEBUG_PRINT_SERIAL_PORT_DETECT_EN), //< Debug print cable detect
  BSBLN (BLDCFG_FCH_ESPI_ABL_INIT_ENABLE),
  BSBLN (BLDCFG_FCH_ESPI_IO80_ENABLE),
  BSBLN (BLDCFG_FCH_ESPI_KBC6064_ENABLE),
  BSU08 (BLDCFG_FCH_ESPI_CLOCK),
  BSU08 (BLDCFG_FCH_ESPI_IOMODE),
  BSU08 (BLDCFG_FCH_ESPI_ALERT_MODE),
  BSU08 (BLDCFG_FCH_ESPI_IORANGE0_SIZE),
  BSU08 (BLDCFG_FCH_ESPI_IORANGE1_SIZE),
  BSU08 (BLDCFG_FCH_ESPI_IORANGE2_SIZE),
  BSU08 (BLDCFG_FCH_ESPI_IORANGE3_SIZE),
  BSU16 (BLDCFG_FCH_ESPI_IORANGE0_BASE),
  BSU16 (BLDCFG_FCH_ESPI_IORANGE1_BASE),
  BSU16 (BLDCFG_FCH_ESPI_IORANGE2_BASE),
  BSU16 (BLDCFG_FCH_ESPI_IORANGE3_BASE),
  BSU16 (BLDCFG_FCH_ESPI_MMIORANGE0_SIZE),
  BSU16 (BLDCFG_FCH_ESPI_MMIORANGE1_SIZE),
  BSU16 (BLDCFG_FCH_ESPI_MMIORANGE2_SIZE),
  BSU16 (BLDCFG_FCH_ESPI_MMIORANGE3_SIZE),
  BSU32 (BLDCFG_FCH_ESPI_MMIORANGE0_BASE),
  BSU32 (BLDCFG_FCH_ESPI_MMIORANGE1_BASE),
  BSU32 (BLDCFG_FCH_ESPI_MMIORANGE2_BASE),
  BSU32 (BLDCFG_FCH_ESPI_MMIORANGE3_BASE),
  BSU08 (0xFF)
};

APCB_TYPE_DATA_END_SIGNATURE();


int main(IN int argc, IN char * argv[])
{
  return 0;
}





