/*****************************************************************************
 *
 * Copyright (C) 2016-2022 Advanced Micro Devices, Inc. All rights reserved.
 *
 *******************************************************************************
 */

#ifndef _APCB_V2_TOKEN_ID_H_
#define _APCB_V2_TOKEN_ID_H_
//
// @APCB_START
//

#if APCB_V3_UID_USED
#define APCB_TOKEN_V2_STYLE  0
#else
#define APCB_TOKEN_V2_STYLE  1
#endif

#if APCB_TOKEN_V2_STYLE

//
// The enumerator should always grow at the end of the list of each component
// Obsolete tokens should be preserved to maintain backward compatibility
//
typedef enum {
  APCB_TOKEN_CONFIG_PSP_BEGIN = 0x0,
  APCB_TOKEN_UID_PSP_ENABLE_DEBUG_MODE,
  APCB_TOKEN_UID_PSP_TP_PORT,
  APCB_TOKEN_UID_PSP_ERROR_DISPLAY,
  APCB_TOKEN_UID_PSP_EVENT_LOG_DISPLAY,
  APCB_TOKEN_UID_PSP_STOP_ON_ERROR,
  APCB_TOKEN_UID_PSP_SYSHUB_WDT_INTERVAL,
  APCB_TOKEN_CONFIG_PSP_END,
  APCB_TOKEN_CONFIG_CCX_BEGIN = 0x100,
  APCB_TOKEN_UID_CCX_MIN_SEV_ASID,
  APCB_TOKEN_UID_CCX_SEV_ASID_COUNT,
  APCB_TOKEN_CONFIG_CCX_END,
  APCB_TOKEN_CONFIG_DF_BEGIN = 0x300,
  APCB_TOKEN_UID_DF_GMI_ENCRYPT,
  APCB_TOKEN_UID_DF_XGMI_ENCRYPT,
  APCB_TOKEN_UID_DF_SAVE_RESTORE_MEM_ENCRYPT,
  APCB_TOKEN_UID_DF_SYS_STORAGE_AT_TOP_OF_MEM,
  APCB_TOKEN_UID_DF_PROBE_FILTER,
  APCB_TOKEN_UID_DF_BOTTOMIO,
  APCB_TOKEN_UID_DF_MEM_INTERLEAVING,
  APCB_TOKEN_UID_DF_MEM_INTERLEAVING_SIZE,
  APCB_TOKEN_UID_DF_CHAN_INTLV_HASH,
  APCB_TOKEN_UID_DF_PCI_MMIO_SIZE,
  APCB_TOKEN_UID_DF_CAKE_CRC_THRESH_PERF_BOUNDS,
  APCB_TOKEN_UID_DF_MEM_CLEAR,
  APCB_TOKEN_UID_DF3_XGMI2_LINK_CFG,
  APCB_TOKEN_UID_DF_GMI2_REPLAY,
  APCB_TOKEN_UID_DF_DRAM_NPS,
  APCB_TOKEN_UID_DF_INVERT_DRAM_MAP,
  APCB_TOKEN_UID_DF_4LINK_MAX_XGMI_SPEED,
  APCB_TOKEN_UID_DF_3LINK_MAX_XGMI_SPEED
  APCB_TOKEN_CONFIG_DF_END,
  APCB_TOKEN_CONFIG_MEM_BEGIN = 0x700,
  APCB_TOKEN_UID_BOTTOMIO,
  APCB_TOKEN_UID_MEMHOLEREMAPPING,
  APCB_TOKEN_UID_LIMITMEMORYTOBELOW1TB,
  APCB_TOKEN_UID_USERTIMINGMODE,
  APCB_TOKEN_UID_MEMCLOCKVALUE,
  APCB_TOKEN_UID_ENABLECHIPSELECTINTLV,
  APCB_TOKEN_UID_ENABLECHANNELINTLV,
  APCB_TOKEN_UID_ENABLEECCFEATURE,
  APCB_TOKEN_UID_ENABLEPOWERDOWN,
  APCB_TOKEN_UID_ENABLEPARITY,
  APCB_TOKEN_UID_ENABLEBANKSWIZZLE,
  APCB_TOKEN_UID_ENABLEMEMCLR,
  APCB_TOKEN_UID_UMAMODE,
  APCB_TOKEN_UID_UMASIZE,
  APCB_TOKEN_UID_MEMRESTORECTL,
  APCB_TOKEN_UID_ISCAPSULEMODE,
  APCB_TOKEN_UID_FORCETRAINMODE,
  APCB_TOKEN_UID_DIMMTYPEUSEDINMIXEDCONFIG,
  APCB_TOKEN_UID_AMPENABLE,
  APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATE,
  APCB_TOKEN_UID_PMUTRAINMODE,
  APCB_TOKEN_UID_ECCREDIRECTION,
  APCB_TOKEN_UID_SCRUBDRAMRATE,
  APCB_TOKEN_UID_SCRUBL2RATE,
  APCB_TOKEN_UID_SCRUBL3RATE,
  APCB_TOKEN_UID_SCRUBICRATE,
  APCB_TOKEN_UID_SCRUBDCRATE,
  APCB_TOKEN_UID_ECCSYNCFLOOD,
  APCB_TOKEN_UID_ECCSYMBOLSIZE,
  APCB_TOKEN_UID_DQSTRAININGCONTROL,
  APCB_TOKEN_UID_UMAABOVE4G,
  APCB_TOKEN_UID_UMAALIGNMENT,
  APCB_TOKEN_UID_MEMORYALLCLOCKSON,
  APCB_TOKEN_UID_MEMORYBUSFREQUENCYLIMIT,
  APCB_TOKEN_UID_POWERDOWNMODE,
  APCB_TOKEN_UID_IGNORESPDCHECKSUM,
  APCB_TOKEN_UID_MEMORYMODEUNGANGED,
  APCB_TOKEN_UID_MEMORYQUADRANKCAPABLE,
  APCB_TOKEN_UID_MEMORYRDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYLRDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYUDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYSODIMMCAPABLE,
  APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATEEN,
  APCB_TOKEN_UID_DIMMTYPEDDDR4CAPABLE,
  APCB_TOKEN_UID_DIMMTYPEDDDR3CAPABLE,
  APCB_TOKEN_UID_DIMMTYPELPDDDR3CAPABLE,
  APCB_TOKEN_UID_ENABLEZQRESET,
  APCB_TOKEN_UID_ENABLEBANKGROUPSWAP,
  APCB_TOKEN_UID_ODTSCMDTHROTEN,
  APCB_TOKEN_UID_SWCMDTHROTEN,
  APCB_TOKEN_UID_FORCEPWRDOWNTHROTEN,
  APCB_TOKEN_UID_ODTSCMDTHROTCYC,
  APCB_TOKEN_UID_SWCMDTHROTCYC,
  APCB_TOKEN_UID_DIMMSENSORCONF,
  APCB_TOKEN_UID_DIMMSENSORUPPER,
  APCB_TOKEN_UID_DIMMSENSORLOWER,
  APCB_TOKEN_UID_DIMMSENSORCRITICAL,
  APCB_TOKEN_UID_DIMMSENSORRESOLUTION,
  APCB_TOKEN_UID_AUTOREFFINEGRANMODE,
  APCB_TOKEN_UID_ENABLEMEMPSTATE,
  APCB_TOKEN_UID_SOLDERDOWNDRAM,
  APCB_TOKEN_UID_DDRROUTEBALANCEDTEE,
  APCB_TOKEN_UID_MEM_MBIST_TEST_ENABLE,
  APCB_TOKEN_UID_MEM_MBIST_SUBTEST_TYPE,
  APCB_TOKEN_UID_MEM_MBIST_AGGRESOR_ON,
  APCB_TOKEN_UID_MEM_MBIST_HALT_ON_ERROR,
  APCB_TOKEN_UID_MEM_CPU_VREF_RANGE,
  APCB_TOKEN_UID_MEM_DRAM_VREF_RANGE,
  APCB_TOKEN_UID_MEM_TSME_ENABLE,
  APCB_TOKEN_UID_MEM_NVDIMM_POWER_SOURCE,
  APCB_TOKEN_UID_MEM_DATA_POISON,
  APCB_TOKEN_UID_MEM_DATA_SCRAMBLE,
  APCB_TOKEN_UID_MEM_PS_ERROR_HANDLING,
  APCB_TOKEN_UID_MEM_TEMP_CONTROLLED_REFRESH_EN,
  APCB_TOKEN_UID_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT,
  APCB_TOKEN_UID_ENABLEBANKGROUPSWAPALT,
  APCB_TOKEN_UID_UECC_RETRY_DDR4,
  APCB_TOKEN_UID_POST_PACKAGE_REPAIR_ENABLE,
  APCB_TOKEN_UID_MEM_TEMP_CONTROLLED_EXTENDED_REFRESH_EN,
  APCB_TOKEN_UID_MEM_AGESA_EXTENDED_MEM_TEST_EN,
  APCB_TOKEN_UID_MEM_MBIST_AGGRESSORS_CHNL,
  APCB_TOKEN_UID_MEM_MBIST_PATTERN_LENGTH,
  APCB_TOKEN_UID_MEM_MBIST_PATTERN_SELECT,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_CTRL,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL_ECC,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_VAL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_CTRL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL_ECC,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_VAL,
  APCB_TOKEN_UID_MEM_MBIST_DATA_EYE_TYPE,
  APCB_TOKEN_UID_MEM_MBIST_WORST_CASE_GRAN,
  APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP,
  APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_TIMING_STEP,
  APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP,
  APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP,
  APCB_TOKEN_CONFIG_MEM_END,
  APCB_TOKEN_CONFIG_GNB_BEGIN = 0x1800,
  APCB_TOKEN_UID_BMC_SOCKET_NUMBER,
  APCB_TOKEN_UID_BMC_START_LANE,
  APCB_TOKEN_UID_BMC_END_LANE,
  APCB_TOKEN_UID_BMC_DEVICE,
  APCB_TOKEN_UID_BMC_FUNCTION,
  APCB_TOKEN_UID_PCIE_RESET_CONTROL,
  APCB_TOKEN_CONFIG_GNB_END,
  APCB_TOKEN_CONFIG_FCH_BEGIN = 0x1C00,
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_ENABLE,
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_SERIAL_PORT,
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_BASIC_ENABLE,
  APCB_TOKEN_CONFIG_FCH_END,
  APCB_TOKEN_CONFIG_LIMIT = 0x1FFF
} APCB_PARAM_CONFIG_TOKEN;

// Note: Ensure that the token name matches the variable name in CBS xml file/
//       ApcbAutoGen.h file in Resource folder in CBS package.
//
// CBS CMN APCB Tokens
//
#define APCB_TOKEN_CBS_CMN_BEGIN 0x0000
#define APCB_TOKEN_UID_CBS_DF_CMN_GMI_ENCRYPTION 0x0001 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_X_GMI_ENCRYPTION 0x0002 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CC6_MEM_ENCRYPTION 0x0003 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CC6_ALLOCATION_SCHEME 0x0004 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_SYS_PROBE_FILTER 0x0005 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_INTLV 0x0006 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_INTLV_SIZE 0x0007 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CHNL_INTLV_HASH 0x0008 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4 0x0009
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4 0x000A
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4 0x000B
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASHING_DDR4 0x000C
#define APCB_TOKEN_UID_CBS_CMN_MEM_SPEED_DDR4 0x000D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCL_DDR4 0x000E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDRD_DDR4 0x000F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDWR_DDR4 0x0010
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRP_DDR4 0x0011
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRAS_DDR4 0x0012
#define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_POISONING_DDR4 0x0013
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4 0x0014
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4 0x0015
#define APCB_TOKEN_UID_CBS_CMN_MEM_TSME_DDR4 0x0016
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_DDR4 0x0017
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_MODE 0x0018
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_VERSION 0x0019
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION 0x001A
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE 0x001B
#define APCB_TOKEN_UID_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT 0x001C // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4 0x001D
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_EN 0x001E
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_SUB_TEST 0x001F
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_CLEAR 0x0020 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4 0x0021
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_DDR4 0x0022
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_S_DDR4 0x0023
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_L_DDR4 0x0024
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4 0x0025
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_DDR4 0x0026
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_S_DDR4 0x0027
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_L_DDR4 0x0028
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4 0x0029
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_DDR4 0x002A
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4 0x002B
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4 0x002C
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4 0x002D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4 0x002E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4 0x002F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4 0x0030
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4 0x0031
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC_DDR4 0x0032
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4 0x0033
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_DDR4 0x0034
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4 0x0035
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_DDR4 0x0036
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT 0x0037
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4 0x0038
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4 0x0039
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4 0x003A
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4 0x003B
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4 0x003C
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4 0x003D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4 0x003E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDWR_DDR4 0x003F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRRD_DDR4 0x0040
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRTP_DDR4 0x0041
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCWL_DDR4 0x0042
#define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4 0x0043
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4 0x0044
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4 0x0045
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4 0x0046
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCKE_DDR4 0x0047
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4 0x0048
#define APCB_TOKEN_UID_CBS_CMN_CLDO_VDDP_CTL 0x0049
#define APCB_TOKEN_UID_CBS_CMN_CLDOVDD_PVOLTAGE 0x004A
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4 0x004B
#define APCB_TOKEN_UID_CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4 0x004C
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_AGGRESSORS 0x004D
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT 0x004E
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4 0x004F
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_TIMING_CTL_DDR4 0x0050
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_SETUP_DDR4 0x0051
#define APCB_TOKEN_UID_CBS_CMN_MEM_CS_ODT_SETUP_DDR4 0x0052
#define APCB_TOKEN_UID_CBS_CMN_MEM_CKE_SETUP_DDR4 0x0053
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_DRV_STREN_CTL_DDR4 0x0054
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CLK_DRV_STREN_DDR4 0x0055
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4 0x0056
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4 0x0057
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CKE_DRV_STREN_DDR4 0x0058
#define APCB_TOKEN_UID_CBS_CPU_RELAXED_EDC_THROTTLING 0x0059
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_ALT_DDR4 0x005A
#define APCB_TOKEN_UID_DF_SYNC_FLOOD_PROP 0x005B
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_DIMM_CONFIG_CHECK 0x005C
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DRAM_ECC_EN_DDR4 0x005D
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4 0x005E
#define APCB_TOKEN_UID_CBS_CMN_CPU_SMU_PSP_PROD_MODE 0x005F
#define APCB_TOKEN_UID_CBS_CMN_MEM_UECC_RETRY_DDR4 0x0060
#define APCB_TOKEN_UID_CBS_DF_CMN_CAKE_CRC_PERF_BOUNDS 0x0061
#define APCB_TOKEN_UID_CBS_DF_CMN_GMI2_REPLAY 0x0062 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_TESTMODE 0x0063
#define APCB_TOKEN_UID_CCX_P0_SETTING  0x0064
#define APCB_TOKEN_UID_CCX_P0_FID  0x0065
#define APCB_TOKEN_UID_CCX_P0_DID  0x0066
#define APCB_TOKEN_UID_CCX_P0_VID  0x0067
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_RM_DDR4 0x0068
#define APCB_TOKEN_UID_CBS_CMN_MEM_AGESA_EXTENDED_MEMORY_TEST 0x0069
#define APCB_TOKEN_UID_XTRIG7_WORKAROUND 0x006A

#define APCB_TOKEN_CBS_CMN_END 0x006B
#define APCB_TOKEN_CBS_CMN_LIMIT 0x1FFF



#else // APCB_TOKEN_V2_STYLE

//
// The enumerator should always grow at the end of the list of each component
// Obsolete tokens should be preserved to maintain backward compatibility
//
typedef enum {
  APCB_TOKEN_CONFIG_PSP_BEGIN = 0x0,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_PSP_ENABLE_DEBUG_MODE,
  APCB_TOKEN_UID_PSP_TP_PORT,
  APCB_TOKEN_UID_PSP_ERROR_DISPLAY,
  APCB_TOKEN_UID_PSP_EVENT_LOG_DISPLAY,
  APCB_TOKEN_UID_PSP_STOP_ON_ERROR,
  APCB_TOKEN_UID_PSP_SYSHUB_WDT_INTERVAL,
#endif
  APCB_TOKEN_CONFIG_PSP_END,
  APCB_TOKEN_CONFIG_CCX_BEGIN = 0x100,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_CCX_MIN_SEV_ASID,
  APCB_TOKEN_UID_CCX_SEV_ASID_COUNT,
#endif
  APCB_TOKEN_CONFIG_CCX_END,
  APCB_TOKEN_CONFIG_DF_BEGIN = 0x300,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_DF_GMI_ENCRYPT,
  APCB_TOKEN_UID_DF_XGMI_ENCRYPT,
  APCB_TOKEN_UID_DF_SAVE_RESTORE_MEM_ENCRYPT,
  APCB_TOKEN_UID_DF_SYS_STORAGE_AT_TOP_OF_MEM,
  APCB_TOKEN_UID_DF_PROBE_FILTER,
  APCB_TOKEN_UID_DF_BOTTOMIO,
  APCB_TOKEN_UID_DF_MEM_INTERLEAVING,
  APCB_TOKEN_UID_DF_MEM_INTERLEAVING_SIZE,
  APCB_TOKEN_UID_DF_CHAN_INTLV_HASH,
  APCB_TOKEN_UID_DF_PCI_MMIO_SIZE,
  APCB_TOKEN_UID_DF_CAKE_CRC_THRESH_PERF_BOUNDS,
  APCB_TOKEN_UID_DF_MEM_CLEAR,
  APCB_TOKEN_UID_DF3_XGMI2_LINK_CFG,
  APCB_TOKEN_UID_DF_GMI2_REPLAY,
  APCB_TOKEN_UID_DF_DRAM_NPS,
  APCB_TOKEN_UID_DF_INVERT_DRAM_MAP,
  APCB_TOKEN_UID_DF_4LINK_MAX_XGMI_SPEED,
  APCB_TOKEN_UID_DF_3LINK_MAX_XGMI_SPEED
#endif
  APCB_TOKEN_CONFIG_DF_END,
  APCB_TOKEN_CONFIG_MEM_BEGIN = 0x700,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_BOTTOMIO,
  APCB_TOKEN_UID_MEMHOLEREMAPPING,
  APCB_TOKEN_UID_LIMITMEMORYTOBELOW1TB,
  APCB_TOKEN_UID_USERTIMINGMODE,
  APCB_TOKEN_UID_MEMCLOCKVALUE,
  APCB_TOKEN_UID_ENABLECHIPSELECTINTLV,
  APCB_TOKEN_UID_ENABLECHANNELINTLV,
  APCB_TOKEN_UID_ENABLEECCFEATURE,
  APCB_TOKEN_UID_ENABLEPOWERDOWN,
  APCB_TOKEN_UID_ENABLEPARITY,
  APCB_TOKEN_UID_ENABLEBANKSWIZZLE,
  APCB_TOKEN_UID_ENABLEMEMCLR,
  APCB_TOKEN_UID_UMAMODE,
  APCB_TOKEN_UID_UMASIZE,
  APCB_TOKEN_UID_MEMRESTORECTL,
  APCB_TOKEN_UID_ISCAPSULEMODE,
  APCB_TOKEN_UID_FORCETRAINMODE,
  APCB_TOKEN_UID_DIMMTYPEUSEDINMIXEDCONFIG,
  APCB_TOKEN_UID_AMPENABLE,
  APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATE,
  APCB_TOKEN_UID_PMUTRAINMODE,
  APCB_TOKEN_UID_ECCREDIRECTION,
  APCB_TOKEN_UID_SCRUBDRAMRATE,
  APCB_TOKEN_UID_SCRUBL2RATE,
  APCB_TOKEN_UID_SCRUBL3RATE,
  APCB_TOKEN_UID_SCRUBICRATE,
  APCB_TOKEN_UID_SCRUBDCRATE,
  APCB_TOKEN_UID_ECCSYNCFLOOD,
  APCB_TOKEN_UID_ECCSYMBOLSIZE,
  APCB_TOKEN_UID_DQSTRAININGCONTROL,
  APCB_TOKEN_UID_UMAABOVE4G,
  APCB_TOKEN_UID_UMAALIGNMENT,
  APCB_TOKEN_UID_MEMORYALLCLOCKSON,
  APCB_TOKEN_UID_MEMORYBUSFREQUENCYLIMIT,
  APCB_TOKEN_UID_POWERDOWNMODE,
  APCB_TOKEN_UID_IGNORESPDCHECKSUM,
  APCB_TOKEN_UID_MEMORYMODEUNGANGED,
  APCB_TOKEN_UID_MEMORYQUADRANKCAPABLE,
  APCB_TOKEN_UID_MEMORYRDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYLRDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYUDIMMCAPABLE,
  APCB_TOKEN_UID_MEMORYSODIMMCAPABLE,
  APCB_TOKEN_UID_DRAMDOUBLEREFRESHRATEEN,
  APCB_TOKEN_UID_DIMMTYPEDDDR4CAPABLE,
  APCB_TOKEN_UID_DIMMTYPEDDDR3CAPABLE,
  APCB_TOKEN_UID_DIMMTYPELPDDDR3CAPABLE,
  APCB_TOKEN_UID_ENABLEZQRESET,
  APCB_TOKEN_UID_ENABLEBANKGROUPSWAP,
  APCB_TOKEN_UID_ODTSCMDTHROTEN,
  APCB_TOKEN_UID_SWCMDTHROTEN,
  APCB_TOKEN_UID_FORCEPWRDOWNTHROTEN,
  APCB_TOKEN_UID_ODTSCMDTHROTCYC,
  APCB_TOKEN_UID_SWCMDTHROTCYC,
  APCB_TOKEN_UID_DIMMSENSORCONF,
  APCB_TOKEN_UID_DIMMSENSORUPPER,
  APCB_TOKEN_UID_DIMMSENSORLOWER,
  APCB_TOKEN_UID_DIMMSENSORCRITICAL,
  APCB_TOKEN_UID_DIMMSENSORRESOLUTION,
  APCB_TOKEN_UID_AUTOREFFINEGRANMODE,
  APCB_TOKEN_UID_ENABLEMEMPSTATE,
  APCB_TOKEN_UID_SOLDERDOWNDRAM,
  APCB_TOKEN_UID_DDRROUTEBALANCEDTEE,
  APCB_TOKEN_UID_MEM_MBIST_TEST_ENABLE,
  APCB_TOKEN_UID_MEM_MBIST_SUBTEST_TYPE,
  APCB_TOKEN_UID_MEM_MBIST_AGGRESOR_ON,
  APCB_TOKEN_UID_MEM_MBIST_HALT_ON_ERROR,
  APCB_TOKEN_UID_MEM_CPU_VREF_RANGE,
  APCB_TOKEN_UID_MEM_DRAM_VREF_RANGE,
  APCB_TOKEN_UID_MEM_TSME_ENABLE,
  APCB_TOKEN_UID_MEM_NVDIMM_POWER_SOURCE,
  APCB_TOKEN_UID_MEM_DATA_POISON,
  APCB_TOKEN_UID_MEM_DATA_SCRAMBLE,
  APCB_TOKEN_UID_MEM_PS_ERROR_HANDLING,
  APCB_TOKEN_UID_MEM_TEMP_CONTROLLED_REFRESH_EN,
  APCB_TOKEN_UID_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT,
  APCB_TOKEN_UID_ENABLEBANKGROUPSWAPALT,
  APCB_TOKEN_UID_UECC_RETRY_DDR4,
  APCB_TOKEN_UID_POST_PACKAGE_REPAIR_ENABLE,
  APCB_TOKEN_UID_MEM_TEMP_CONTROLLED_EXTENDED_REFRESH_EN,
  APCB_TOKEN_UID_MEM_AGESA_EXTENDED_MEM_TEST_EN,
  APCB_TOKEN_UID_MEM_MBIST_AGGRESSORS_CHNL,
  APCB_TOKEN_UID_MEM_MBIST_PATTERN_LENGTH,
  APCB_TOKEN_UID_MEM_MBIST_PATTERN_SELECT,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_CTRL,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_SEL_ECC,
  APCB_TOKEN_UID_MEM_MBIST_AGGR_STATIC_LANE_VAL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_CTRL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_SEL_ECC,
  APCB_TOKEN_UID_MEM_MBIST_TGT_STATIC_LANE_VAL,
  APCB_TOKEN_UID_MEM_MBIST_DATA_EYE_TYPE,
  APCB_TOKEN_UID_MEM_MBIST_WORST_CASE_GRAN,
  APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_VOLTAGE_STEP,
  APCB_TOKEN_UID_MEM_MBIST_READ_DATA_EYE_TIMING_STEP,
  APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_VOLTAGE_STEP,
  APCB_TOKEN_UID_MEM_MBIST_WRITE_DATA_EYE_TIMING_STEP,
#endif
  APCB_TOKEN_CONFIG_MEM_END,
  APCB_TOKEN_CONFIG_GNB_BEGIN = 0x1800,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_BMC_SOCKET_NUMBER,
  APCB_TOKEN_UID_BMC_START_LANE,
  APCB_TOKEN_UID_BMC_END_LANE,
  APCB_TOKEN_UID_BMC_DEVICE,
  APCB_TOKEN_UID_BMC_FUNCTION,
  APCB_TOKEN_UID_PCIE_RESET_CONTROL,
#endif
  APCB_TOKEN_CONFIG_GNB_END,
  APCB_TOKEN_CONFIG_FCH_BEGIN = 0x1C00,
#if !APCB_V3_UID_USED
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_ENABLE,
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_SERIAL_PORT,
  APCB_TOKEN_UID_FCH_CONSOLE_OUT_BASIC_ENABLE,
#endif
  APCB_TOKEN_CONFIG_FCH_END,
  APCB_TOKEN_CONFIG_LIMIT = 0x1FFF
} APCB_PARAM_CONFIG_TOKEN;

// Note: Ensure that the token name matches the variable name in CBS xml file/
//       ApcbAutoGen.h file in Resource folder in CBS package.
//
// CBS CMN APCB Tokens
//
#define APCB_TOKEN_CBS_CMN_BEGIN 0x0000
#if !APCB_V3_UID_USED
#define APCB_TOKEN_UID_CBS_DF_CMN_GMI_ENCRYPTION 0x0001 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_X_GMI_ENCRYPTION 0x0002 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CC6_MEM_ENCRYPTION 0x0003 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CC6_ALLOCATION_SCHEME 0x0004 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_SYS_PROBE_FILTER 0x0005 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_INTLV 0x0006 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_INTLV_SIZE 0x0007 // Obsolete
#define APCB_TOKEN_UID_CBS_DF_CMN_CHNL_INTLV_HASH 0x0008 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4 0x0009
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4 0x000A
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4 0x000B
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASHING_DDR4 0x000C
#define APCB_TOKEN_UID_CBS_CMN_MEM_SPEED_DDR4 0x000D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCL_DDR4 0x000E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDRD_DDR4 0x000F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCDWR_DDR4 0x0010
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRP_DDR4 0x0011
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRAS_DDR4 0x0012
#define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_POISONING_DDR4 0x0013
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4 0x0014
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4 0x0015
#define APCB_TOKEN_UID_CBS_CMN_MEM_TSME_DDR4 0x0016
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_DDR4 0x0017
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_MODE 0x0018
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_VERSION 0x0019
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION 0x001A
#define APCB_TOKEN_UID_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE 0x001B
#define APCB_TOKEN_UID_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT 0x001C // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4 0x001D
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_EN 0x001E
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_SUB_TEST 0x001F
#define APCB_TOKEN_UID_CBS_DF_CMN_MEM_CLEAR 0x0020 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4 0x0021
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRC_DDR4 0x0022
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_S_DDR4 0x0023
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRRD_L_DDR4 0x0024
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4 0x0025
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TFAW_DDR4 0x0026
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_S_DDR4 0x0027
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWTR_L_DDR4 0x0028
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4 0x0029
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWR_DDR4 0x002A
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4 0x002B
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4 0x002C
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4 0x002D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4 0x002E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4 0x002F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4 0x0030
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4 0x0031
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC_DDR4 0x0032
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4 0x0033
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC2_DDR4 0x0034
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4 0x0035
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRFC4_DDR4 0x0036
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT 0x0037
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4 0x0038
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4 0x0039
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4 0x003A
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4 0x003B
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4 0x003C
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4 0x003D
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4 0x003E
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRDWR_DDR4 0x003F
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TWRRD_DDR4 0x0040
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TRTP_DDR4 0x0041
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCWL_DDR4 0x0042
#define APCB_TOKEN_UID_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4 0x0043
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4 0x0044
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4 0x0045
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4 0x0046
#define APCB_TOKEN_UID_CBS_CMN_MEM_TIMING_TCKE_DDR4 0x0047
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4 0x0048
#define APCB_TOKEN_UID_CBS_CMN_CLDO_VDDP_CTL 0x0049
#define APCB_TOKEN_UID_CBS_CMN_CLDOVDD_PVOLTAGE 0x004A
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4 0x004B
#define APCB_TOKEN_UID_CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4 0x004C
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_AGGRESSORS 0x004D
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT 0x004E
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4 0x004F
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_TIMING_CTL_DDR4 0x0050
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDR_CMD_SETUP_DDR4 0x0051
#define APCB_TOKEN_UID_CBS_CMN_MEM_CS_ODT_SETUP_DDR4 0x0052
#define APCB_TOKEN_UID_CBS_CMN_MEM_CKE_SETUP_DDR4 0x0053
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_DRV_STREN_CTL_DDR4 0x0054
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CLK_DRV_STREN_DDR4 0x0055
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_ADDR_CMD_DRV_STREN_DDR4 0x0056
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CS_ODT_DRV_STREN_DDR4 0x0057
#define APCB_TOKEN_UID_CBS_CMN_MEM_CAD_BUS_CKE_DRV_STREN_DDR4 0x0058
#define APCB_TOKEN_UID_CBS_CPU_RELAXED_EDC_THROTTLING 0x0059
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_ALT_DDR4 0x005A
#define APCB_TOKEN_UID_DF_SYNC_FLOOD_PROP 0x005B
#define APCB_TOKEN_UID_CBS_CMN_MEM_OVERCLOCK_DIMM_CONFIG_CHECK 0x005C
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DRAM_ECC_EN_DDR4 0x005D
#define APCB_TOKEN_UID_CBS_CMN_MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4 0x005E
#define APCB_TOKEN_UID_CBS_CMN_CPU_SMU_PSP_PROD_MODE 0x005F
#define APCB_TOKEN_UID_CBS_CMN_MEM_UECC_RETRY_DDR4 0x0060
#define APCB_TOKEN_UID_CBS_DF_CMN_CAKE_CRC_PERF_BOUNDS 0x0061
#define APCB_TOKEN_UID_CBS_DF_CMN_GMI2_REPLAY 0x0062 // Obsolete
#define APCB_TOKEN_UID_CBS_CMN_MEM_MBIST_TESTMODE 0x0063
#define APCB_TOKEN_UID_CCX_P0_SETTING  0x0064
#define APCB_TOKEN_UID_CCX_P0_FID  0x0065
#define APCB_TOKEN_UID_CCX_P0_DID  0x0066
#define APCB_TOKEN_UID_CCX_P0_VID  0x0067
#define APCB_TOKEN_UID_CBS_CMN_MEM_ADDRESS_HASH_RM_DDR4 0x0068
#define APCB_TOKEN_UID_CBS_CMN_MEM_AGESA_EXTENDED_MEMORY_TEST 0x0069
#define APCB_TOKEN_UID_XTRIG7_WORKAROUND 0x006A

#endif // (APCB_V2_TOKEN_ID_TO_UID == 0)


#define APCB_TOKEN_CBS_CMN_END 0x006B
#define APCB_TOKEN_CBS_CMN_LIMIT 0x1FFF

#endif // APCB_TOKEN_V2_STYLE


#endif // _APCB_V2_TOKEN_ID_H_

