
@echo off

@set APCB_TOOL_PATH=%WORKSPACE%\AgesaModulePkg\AMDTools\ApcbToolV2\Tools
@set APCB_PKG_PATH=%WORKSPACE%\AgesaPkg\Addendum\Apcb
@set APCB_INC_PATH=%APCB_PKG_PATH%\Inc
@set APCB_BOARD_PKG_PATH=%APCB_PKG_PATH%\RavenFp5Udimm


@set APCB_TEMP_PATH=%WORKSPACE%\Build\%PROJECT_PKG%\ApcbToolV2
@set APCB_TOOL_TEMP_PATH=%APCB_TEMP_PATH%\Tools
@set APCB_INC_TEMP_PATH=%APCB_TEMP_PATH%\Inc
@set APCB_BOARD_PKG_TEMP_PATH=%APCB_TEMP_PATH%\External
@set APCB_BUILD_COMMAND=ApcbCreate.bat



::
:: Clean up existing files
::
@if exist %APCB_TEMP_PATH% (
  @rd %APCB_TEMP_PATH% /S /Q
)

@echo D | @xcopy %APCB_TOOL_PATH%\*.*                    %APCB_TOOL_TEMP_PATH% /S /Y
@echo D | @xcopy %APCB_INC_PATH%\*.*                     %APCB_INC_TEMP_PATH% /S /Y
@echo D | @xcopy %APCB_BOARD_PKG_PATH%\*.*               %APCB_BOARD_PKG_TEMP_PATH% /S /Y

::
:: Override platform specific settings
::
@copy %WORKSPACE%\%PROJECT_PKG%\ApcbCustomization\ApcbCustomizedDefinitionsRvFp5.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbCustomizedDefinitions.h
@copy %WORKSPACE%\%PROJECT_PKG%\ApcbCustomization\%APCB_BUILD_COMMAND% %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND%

::[-start-190617-IB06070033-modify]::
::
:: Override autogenerated GBS settings
::
@copy %WORKSPACE%\AmdCbsPkg\Library\Family\0x17\RV\External\ResourceRVFP5\ApcbAutoGenRV.h %APCB_BOARD_PKG_TEMP_PATH%\Include\ApcbAutoGen.h
::[-end-190617-IB06070033-modify]::

@pushd %APCB_BOARD_PKG_TEMP_PATH%

::
:: Customize the APCB tool directory
::
SET TOOL_DIR=%APCB_TOOL_TEMP_PATH%
::
:: Run ApcbCreate twice to work around an issue in finding the bin files
::
echo  %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND%
@call %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND% CLEAN BUILD
@call %APCB_BOARD_PKG_TEMP_PATH%\%APCB_BUILD_COMMAND% CLEAN BUILD
rem if %errorlevel% neq 0 exit

@set CUSTOM_APCB_PATH=%APCB_BOARD_PKG_TEMP_PATH%\Release\

@popd

@goto end

:end
